# Generated by Django 5.1.2 on 2024-11-11 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_correo_electronico_anfitrion'),
    ]

    operations = [
        migrations.AddField(
            model_name='anfitrion',
            name='contratos',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anfitrion',
            name='viviendas_registradas',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela', models.CharField(max_length=100)),
                ('credencial', models.FileField(upload_to='credenciales_estudiantes/')),
                ('contratos', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario')),
            ],
        ),
    ]
