# Generated by Django 5.1.2 on 2024-11-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_remove_anfitrion_usuario_remove_estudiante_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='direccion',
        ),
        migrations.AddField(
            model_name='vivienda',
            name='areas_comunes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='calle',
            field=models.CharField(default='Sin Calle', max_length=255),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='codigo_postal',
            field=models.CharField(default='07000', max_length=5),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='detalles_inmueble',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='detalles_inmueble_compartido',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='electrodomesticos',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='estacionamiento',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='fotos',
            field=models.ImageField(blank=True, null=True, upload_to='viviendas_fotos/'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='muebles',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='numero_exterior',
            field=models.CharField(default='S/N', max_length=10),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='servicios',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='transporte_cercano',
            field=models.JSONField(default=dict),
        ),
    ]
