# Generated by Django 5.1.2 on 2024-11-11 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_remove_vivienda_direccion_vivienda_areas_comunes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='anfitrion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.anfitrion'),
        ),
    ]
