# Generated by Django 5.1.2 on 2024-11-12 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_vivienda_anfitrion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vivienda',
            name='fotos',
        ),
        migrations.CreateModel(
            name='ViviendaFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='viviendas_fotos/')),
                ('vivienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='usuarios.vivienda')),
            ],
        ),
    ]
