# Generated by Django 5.1.2 on 2024-11-13 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_anfitrion_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anfitrion',
            name='user',
        ),
    ]
