# Generated by Django 5.1.2 on 2024-11-19 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_estudiante_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anfitrion',
            name='contratos',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='contratos',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='vivienda_contratada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='estudiante_contratado', to='usuarios.vivienda'),
        ),
        migrations.AddField(
            model_name='vivienda',
            name='precio_renta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('precio_renta', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('archivo_contrato', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('firmado', models.BooleanField(default=False)),
                ('firma_estudiante', models.TextField(blank=True, null=True)),
                ('firma_anfitrion', models.TextField(blank=True, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('anfitrion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='usuarios.anfitrion')),
                ('estudiante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='usuarios.estudiante')),
                ('vivienda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='usuarios.vivienda')),
            ],
        ),
        migrations.CreateModel(
            name='FotoEstadoVivienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='contratos/fotos_vivienda/')),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_estado', to='usuarios.contrato')),
            ],
        ),
    ]
