# Generated by Django 5.1.2 on 2024-11-19 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_remove_anfitrion_contratos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='precio_renta',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
