# Generated by Django 5.1.2 on 2024-11-19 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0013_alter_vivienda_precio_renta'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='fotos_subidas_anfitrion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contrato',
            name='fotos_subidas_estudiante',
            field=models.BooleanField(default=False),
        ),
    ]
