# Generated by Django 5.1.2 on 2024-11-19 21:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0015_contrato_cancelado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
