# Generated by Django 5.1.2 on 2024-11-25 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_alter_contrato_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='areas_comunes',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='detalles_inmueble',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='detalles_inmueble_compartido',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='electrodomesticos',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='estacionamiento',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='muebles',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='servicios',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='transporte_cercano',
            field=models.CharField(max_length=500),
        ),
    ]
