# Generated by Django 5.1.2 on 2024-11-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_alter_vivienda_areas_comunes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vivienda',
            name='areas_comunes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='detalles_inmueble',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='detalles_inmueble_compartido',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='electrodomesticos',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='estacionamiento',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='muebles',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='servicios',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vivienda',
            name='transporte_cercano',
            field=models.TextField(),
        ),
    ]
