# Generated by Django 5.1.2 on 2024-11-27 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_alter_vivienda_areas_comunes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vivienda',
            name='tipo_inmueble',
            field=models.CharField(default='Departamento', max_length=150),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='archivo_contrato',
            field=models.FileField(null=True, upload_to='contratos/'),
        ),
    ]
