# Generated by Django 5.1.2 on 2024-11-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_vivienda_tipo_inmueble_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='archivo_contrato',
            field=models.FileField(blank=True, null=True, upload_to='contratos/'),
        ),
    ]
