# Generated by Django 5.1.2 on 2024-11-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_signaturemodel_file_signaturemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signaturemodel',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='firmas/archivos/'),
        ),
        migrations.AlterField(
            model_name='signaturemodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/imagenes/'),
        ),
    ]
