# Generated by Django 5.1.2 on 2024-11-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_alter_contrato_firma_anfitrion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='firma_estudiante',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/firmas_estudiantes/'),
        ),
    ]
